package ranking

// This file was generated by go:generate
// Do not do any modifications here

import (
	"strings"

	"github.com/Synaxis/nfsc-fesl/backend/model"
)

var (
	getters = map[string]Getter{
		"c_ft": func(p *model.HeroStats) (string, error) {
			if p.FacialHairType == "" {
				return "0", nil
			}
			return p.FacialHairType, nil
		},
		"c_team": func(p *model.HeroStats) (string, error) {
			if p.Faction == "" {
				return "1", nil
			}
			return p.Faction, nil
		},
		"c_hrc": func(p *model.HeroStats) (string, error) {
			if p.HairColor == "" {
				return "1", nil
			}
			return p.HairColor, nil
		},
		"c_hrs": func(p *model.HeroStats) (string, error) {
			if p.HairStyle == "" {
				return "0", nil
			}
			return p.HairStyle, nil
		},
		"c_skc": func(p *model.HeroStats) (string, error) {
			if p.SkinColor == "" {
				return "1", nil
			}
			return p.SkinColor, nil
		},
		"c_ltp": func(p *model.HeroStats) (string, error) {
			if p.CLtp == "" {
				return "9301.0000", nil
			}
			return p.CLtp, nil
		},
		"c_ltm": func(p *model.HeroStats) (string, error) {
			if p.CLtm == "" {
				return "0.0000", nil
			}
			return p.CLtm, nil
		},
		"c_fhrs": func(p *model.HeroStats) (string, error) {
			if p.CFhrs == "" {
				return "0.0000", nil
			}
			return p.CFhrs, nil
		},
		"c_slm": func(p *model.HeroStats) (string, error) {
			if p.CSlm == "" {
				return "0.0000", nil
			}
			return p.CSlm, nil
		},
		"cdm": func(p *model.HeroStats) (string, error) {
			if p.Cdm == "" {
				return "0.0000", nil
			}
			return p.Cdm, nil
		},
		"edm": func(p *model.HeroStats) (string, error) {
			if p.Edm == "" {
				return "0.0000", nil
			}
			return p.Edm, nil
		},
		"c_kit": func(p *model.HeroStats) (string, error) {
			if p.PlayerType == "" {
				return "0", nil
			}
			return p.PlayerType, nil
		},
		"c_wallet_hero": func(p *model.HeroStats) (string, error) {
			if p.HeroPoints == "" {
				return "0.0000", nil
			}
			return p.HeroPoints, nil
		},
		"c_wallet_valor": func(p *model.HeroStats) (string, error) {
			if p.ValorPoints == "" {
				return "0.0000", nil
			}
			return p.ValorPoints, nil
		},
		"games": func(p *model.HeroStats) (string, error) {
			if p.GamesPlayed == "" {
				return "0.000", nil
			}
			return p.GamesPlayed, nil
		},
		"elo": func(p *model.HeroStats) (string, error) {
			if p.Elo == "" {
				return "1000.0000", nil
			}
			return p.Elo, nil
		},
		"level": func(p *model.HeroStats) (string, error) {
			if p.Level == "" {
				return "1", nil
			}
			return p.Level, nil
		},
		"xp": func(p *model.HeroStats) (string, error) {
			if p.XP == "" {
				return "0.0000", nil
			}
			return p.XP, nil
		},
		"ct": func(p *model.HeroStats) (string, error) {
			if p.TimePlayed == "" {
				return "0.0000", nil
			}
			return p.TimePlayed, nil
		},
		"ki": func(p *model.HeroStats) (string, error) {
			if p.Kills == "" {
				return "0.0000", nil
			}
			return p.Kills, nil
		},
		"dt": func(p *model.HeroStats) (string, error) {
			if p.Deaths == "" {
				return "0.0000", nil
			}
			return p.Deaths, nil
		},
		"su": func(p *model.HeroStats) (string, error) {
			if p.Suicides == "" {
				return "0.0000", nil
			}
			return p.Suicides, nil
		},
		"win": func(p *model.HeroStats) (string, error) {
			if p.Wins == "" {
				return "0.0000", nil
			}
			return p.Wins, nil
		},
		"los": func(p *model.HeroStats) (string, error) {
			if p.Losses == "" {
				return "0.0000", nil
			}
			return p.Losses, nil
		},
		"fi": func(p *model.HeroStats) (string, error) {
			if p.BulletsFired == "" {
				return "0.0000", nil
			}
			return p.BulletsFired, nil
		},
		"hi": func(p *model.HeroStats) (string, error) {
			if p.BulletsHit == "" {
				return "0.0000", nil
			}
			return p.BulletsHit, nil
		},
		"rs": func(p *model.HeroStats) (string, error) {
			if p.Score == "" {
				return "0.0000", nil
			}
			return p.Score, nil
		},
		"ts": func(p *model.HeroStats) (string, error) {
			if p.TeamScore == "" {
				return "0.0000", nil
			}
			return p.TeamScore, nil
		},
		"ss": func(p *model.HeroStats) (string, error) {
			if p.SkillScore == "" {
				return "0.0000", nil
			}
			return p.SkillScore, nil
		},
		"cs": func(p *model.HeroStats) (string, error) {
			if p.CaptureScore == "" {
				return "0.0000", nil
			}
			return p.CaptureScore, nil
		},
		"prs": func(p *model.HeroStats) (string, error) {
			if p.PrestigeLevel == "" {
				return "0.0000", nil
			}
			return p.PrestigeLevel, nil
		},
		"ppt": func(p *model.HeroStats) (string, error) {
			if p.PrestigePoints == "" {
				return "0.0000", nil
			}
			return p.PrestigePoints, nil
		},
		"c_tut": func(p *model.HeroStats) (string, error) {
			if p.PlayedTutorial == "" {
				return "1.0000", nil
			}
			return p.PlayedTutorial, nil
		},
		"awybt": func(p *model.HeroStats) (string, error) {
			if p.AwayBonusMedal == "" {
				return "0.0000", nil
			}
			return p.AwayBonusMedal, nil
		},
		"dmc": func(p *model.HeroStats) (string, error) {
			if p.DailyMissionsCompleted == "" {
				return "0.0000", nil
			}
			return p.DailyMissionsCompleted, nil
		},
		"gsco": func(p *model.HeroStats) (string, error) {
			if p.Globals.GlobalScore == "" {
				return "0.0000", nil
			}
			return p.Globals.GlobalScore, nil
		},
		"expts": func(p *model.HeroStats) (string, error) {
			if p.Globals.GlobalXP == "" {
				return "0.0000", nil
			}
			return p.Globals.GlobalXP, nil
		},
		"bnspt": func(p *model.HeroStats) (string, error) {
			if p.Globals.GlobalAwayBonus == "" {
				return "0.0000", nil
			}
			return p.Globals.GlobalAwayBonus, nil
		},
		"c_aprweb0": func(p *model.HeroStats) (string, error) {
			if p.Medals.WebKey[0] == "" {
				return "0", nil
			}
			return p.Medals.WebKey[0], nil
		},
		"c_aprweb1": func(p *model.HeroStats) (string, error) {
			if p.Medals.WebKey[1] == "" {
				return "0", nil
			}
			return p.Medals.WebKey[1], nil
		},
		"c_aprweb2": func(p *model.HeroStats) (string, error) {
			if p.Medals.WebKey[2] == "" {
				return "0", nil
			}
			return p.Medals.WebKey[2], nil
		},
		"c_aprweb3": func(p *model.HeroStats) (string, error) {
			if p.Medals.WebKey[3] == "" {
				return "0", nil
			}
			return p.Medals.WebKey[3], nil
		},
		"c_aprweb4": func(p *model.HeroStats) (string, error) {
			if p.Medals.WebKey[4] == "" {
				return "0", nil
			}
			return p.Medals.WebKey[4], nil
		},
		"c_aprweb5": func(p *model.HeroStats) (string, error) {
			if p.Medals.WebKey[5] == "" {
				return "0", nil
			}
			return p.Medals.WebKey[5], nil
		},
		"c_aprweb6": func(p *model.HeroStats) (string, error) {
			if p.Medals.WebKey[6] == "" {
				return "0", nil
			}
			return p.Medals.WebKey[6], nil
		},
		"aw6000": func(p *model.HeroStats) (string, error) {
			if p.Medals.Awards[6000] == "" {
				return "6000", nil
			}
			return p.Medals.Awards[6000], nil
		},
		"aw6001": func(p *model.HeroStats) (string, error) {
			if p.Medals.Awards[6001] == "" {
				return "6000", nil
			}
			return p.Medals.Awards[6001], nil
		},
		"aw6002": func(p *model.HeroStats) (string, error) {
			if p.Medals.Awards[6002] == "" {
				return "6000", nil
			}
			return p.Medals.Awards[6002], nil
		},
		"aw6003": func(p *model.HeroStats) (string, error) {
			if p.Medals.Awards[6003] == "" {
				return "6000", nil
			}
			return p.Medals.Awards[6003], nil
		},
		"aw6004": func(p *model.HeroStats) (string, error) {
			if p.Medals.Awards[6004] == "" {
				return "6000", nil
			}
			return p.Medals.Awards[6004], nil
		},
		"aw6005": func(p *model.HeroStats) (string, error) {
			if p.Medals.Awards[6005] == "" {
				return "6000", nil
			}
			return p.Medals.Awards[6005], nil
		},
		"aw6006": func(p *model.HeroStats) (string, error) {
			if p.Medals.Awards[6006] == "" {
				return "6000", nil
			}
			return p.Medals.Awards[6006], nil
		},
		"aw6007": func(p *model.HeroStats) (string, error) {
			if p.Medals.Awards[6007] == "" {
				return "6000", nil
			}
			return p.Medals.Awards[6007], nil
		},
		"aw6008": func(p *model.HeroStats) (string, error) {
			if p.Medals.Awards[6008] == "" {
				return "6000", nil
			}
			return p.Medals.Awards[6008], nil
		},
		"aw6009": func(p *model.HeroStats) (string, error) {
			if p.Medals.Awards[6009] == "" {
				return "6000", nil
			}
			return p.Medals.Awards[6009], nil
		},
		"aw6010": func(p *model.HeroStats) (string, error) {
			if p.Medals.Awards[6010] == "" {
				return "6000", nil
			}
			return p.Medals.Awards[6010], nil
		},
		"aw6011": func(p *model.HeroStats) (string, error) {
			if p.Medals.Awards[6011] == "" {
				return "6000", nil
			}
			return p.Medals.Awards[6011], nil
		},
		"aw6012": func(p *model.HeroStats) (string, error) {
			if p.Medals.Awards[6012] == "" {
				return "6000", nil
			}
			return p.Medals.Awards[6012], nil
		},
		"aw6013": func(p *model.HeroStats) (string, error) {
			if p.Medals.Awards[6013] == "" {
				return "6000", nil
			}
			return p.Medals.Awards[6013], nil
		},
		"aw6014": func(p *model.HeroStats) (string, error) {
			if p.Medals.Awards[6014] == "" {
				return "6000", nil
			}
			return p.Medals.Awards[6014], nil
		},
		"aw6015": func(p *model.HeroStats) (string, error) {
			if p.Medals.Awards[6015] == "" {
				return "6000", nil
			}
			return p.Medals.Awards[6015], nil
		},
		"aw6016": func(p *model.HeroStats) (string, error) {
			if p.Medals.Awards[6016] == "" {
				return "6000", nil
			}
			return p.Medals.Awards[6016], nil
		},
		"aw6017": func(p *model.HeroStats) (string, error) {
			if p.Medals.Awards[6017] == "" {
				return "6000", nil
			}
			return p.Medals.Awards[6017], nil
		},
		"aw6018": func(p *model.HeroStats) (string, error) {
			if p.Medals.Awards[6018] == "" {
				return "6000", nil
			}
			return p.Medals.Awards[6018], nil
		},
		"aw6019": func(p *model.HeroStats) (string, error) {
			if p.Medals.Awards[6019] == "" {
				return "6000", nil
			}
			return p.Medals.Awards[6019], nil
		},
		"aw6020": func(p *model.HeroStats) (string, error) {
			if p.Medals.Awards[6020] == "" {
				return "6000", nil
			}
			return p.Medals.Awards[6020], nil
		},
		"aw6021": func(p *model.HeroStats) (string, error) {
			if p.Medals.Awards[6021] == "" {
				return "6000", nil
			}
			return p.Medals.Awards[6021], nil
		},
		"aw6022": func(p *model.HeroStats) (string, error) {
			if p.Medals.Awards[6022] == "" {
				return "6000", nil
			}
			return p.Medals.Awards[6022], nil
		},
		"aw6023": func(p *model.HeroStats) (string, error) {
			if p.Medals.Awards[6023] == "" {
				return "6000", nil
			}
			return p.Medals.Awards[6023], nil
		},
		"aw6024": func(p *model.HeroStats) (string, error) {
			if p.Medals.Awards[6024] == "" {
				return "6000", nil
			}
			return p.Medals.Awards[6024], nil
		},
		"aw6025": func(p *model.HeroStats) (string, error) {
			if p.Medals.Awards[6025] == "" {
				return "6000", nil
			}
			return p.Medals.Awards[6025], nil
		},
		"aw6026": func(p *model.HeroStats) (string, error) {
			if p.Medals.Awards[6026] == "" {
				return "6000", nil
			}
			return p.Medals.Awards[6026], nil
		},
		"aw6027": func(p *model.HeroStats) (string, error) {
			if p.Medals.Awards[6027] == "" {
				return "6000", nil
			}
			return p.Medals.Awards[6027], nil
		},
		"aw6028": func(p *model.HeroStats) (string, error) {
			if p.Medals.Awards[6028] == "" {
				return "6000", nil
			}
			return p.Medals.Awards[6028], nil
		},
		"aw6029": func(p *model.HeroStats) (string, error) {
			if p.Medals.Awards[6029] == "" {
				return "6000", nil
			}
			return p.Medals.Awards[6029], nil
		},
		"aw6030": func(p *model.HeroStats) (string, error) {
			if p.Medals.Awards[6030] == "" {
				return "6000", nil
			}
			return p.Medals.Awards[6030], nil
		},
		"aw6031": func(p *model.HeroStats) (string, error) {
			if p.Medals.Awards[6031] == "" {
				return "6000", nil
			}
			return p.Medals.Awards[6031], nil
		},
		"aw6032": func(p *model.HeroStats) (string, error) {
			if p.Medals.Awards[6032] == "" {
				return "6000", nil
			}
			return p.Medals.Awards[6032], nil
		},
		"aw6033": func(p *model.HeroStats) (string, error) {
			if p.Medals.Awards[6033] == "" {
				return "6000", nil
			}
			return p.Medals.Awards[6033], nil
		},
		"aw6034": func(p *model.HeroStats) (string, error) {
			if p.Medals.Awards[6034] == "" {
				return "6000", nil
			}
			return p.Medals.Awards[6034], nil
		},
		"aw6035": func(p *model.HeroStats) (string, error) {
			if p.Medals.Awards[6035] == "" {
				return "6000", nil
			}
			return p.Medals.Awards[6035], nil
		},
		"aw6036": func(p *model.HeroStats) (string, error) {
			if p.Medals.Awards[6036] == "" {
				return "6000", nil
			}
			return p.Medals.Awards[6036], nil
		},
		"aw6037": func(p *model.HeroStats) (string, error) {
			if p.Medals.Awards[6037] == "" {
				return "6000", nil
			}
			return p.Medals.Awards[6037], nil
		},
		"aw6038": func(p *model.HeroStats) (string, error) {
			if p.Medals.Awards[6038] == "" {
				return "6000", nil
			}
			return p.Medals.Awards[6038], nil
		},
		"aw6039": func(p *model.HeroStats) (string, error) {
			if p.Medals.Awards[6039] == "" {
				return "6000", nil
			}
			return p.Medals.Awards[6039], nil
		},
		"aw6040": func(p *model.HeroStats) (string, error) {
			if p.Medals.Awards[6040] == "" {
				return "6000", nil
			}
			return p.Medals.Awards[6040], nil
		},
		"aw6041": func(p *model.HeroStats) (string, error) {
			if p.Medals.Awards[6041] == "" {
				return "6000", nil
			}
			return p.Medals.Awards[6041], nil
		},
		"aw6042": func(p *model.HeroStats) (string, error) {
			if p.Medals.Awards[6042] == "" {
				return "6000", nil
			}
			return p.Medals.Awards[6042], nil
		},
		"aw6043": func(p *model.HeroStats) (string, error) {
			if p.Medals.Awards[6043] == "" {
				return "6000", nil
			}
			return p.Medals.Awards[6043], nil
		},
		"aw6044": func(p *model.HeroStats) (string, error) {
			if p.Medals.Awards[6044] == "" {
				return "6000", nil
			}
			return p.Medals.Awards[6044], nil
		},
		"aw6045": func(p *model.HeroStats) (string, error) {
			if p.Medals.Awards[6045] == "" {
				return "6000", nil
			}
			return p.Medals.Awards[6045], nil
		},
		"aw6046": func(p *model.HeroStats) (string, error) {
			if p.Medals.Awards[6046] == "" {
				return "6000", nil
			}
			return p.Medals.Awards[6046], nil
		},
		"aw6047": func(p *model.HeroStats) (string, error) {
			if p.Medals.Awards[6047] == "" {
				return "6000", nil
			}
			return p.Medals.Awards[6047], nil
		},
		"aw6048": func(p *model.HeroStats) (string, error) {
			if p.Medals.Awards[6048] == "" {
				return "6000", nil
			}
			return p.Medals.Awards[6048], nil
		},
		"aw6049": func(p *model.HeroStats) (string, error) {
			if p.Medals.Awards[6049] == "" {
				return "6000", nil
			}
			return p.Medals.Awards[6049], nil
		},
		"aw6050": func(p *model.HeroStats) (string, error) {
			if p.Medals.Awards[6050] == "" {
				return "6000", nil
			}
			return p.Medals.Awards[6050], nil
		},
		"aw6051": func(p *model.HeroStats) (string, error) {
			if p.Medals.Awards[6051] == "" {
				return "6000", nil
			}
			return p.Medals.Awards[6051], nil
		},
		"aw6052": func(p *model.HeroStats) (string, error) {
			if p.Medals.Awards[6052] == "" {
				return "6000", nil
			}
			return p.Medals.Awards[6052], nil
		},
		"aw6053": func(p *model.HeroStats) (string, error) {
			if p.Medals.Awards[6053] == "" {
				return "6000", nil
			}
			return p.Medals.Awards[6053], nil
		},
		"aw6054": func(p *model.HeroStats) (string, error) {
			if p.Medals.Awards[6054] == "" {
				return "6000", nil
			}
			return p.Medals.Awards[6054], nil
		},
		"aw6055": func(p *model.HeroStats) (string, error) {
			if p.Medals.Awards[6055] == "" {
				return "6000", nil
			}
			return p.Medals.Awards[6055], nil
		},
		"aw6056": func(p *model.HeroStats) (string, error) {
			if p.Medals.Awards[6056] == "" {
				return "6000", nil
			}
			return p.Medals.Awards[6056], nil
		},
		"aw6057": func(p *model.HeroStats) (string, error) {
			if p.Medals.Awards[6057] == "" {
				return "6000", nil
			}
			return p.Medals.Awards[6057], nil
		},
		"aw6058": func(p *model.HeroStats) (string, error) {
			if p.Medals.Awards[6058] == "" {
				return "6000", nil
			}
			return p.Medals.Awards[6058], nil
		},
		"aw6059": func(p *model.HeroStats) (string, error) {
			if p.Medals.Awards[6059] == "" {
				return "6000", nil
			}
			return p.Medals.Awards[6059], nil
		},
		"aw6060": func(p *model.HeroStats) (string, error) {
			if p.Medals.Awards[6060] == "" {
				return "6000", nil
			}
			return p.Medals.Awards[6060], nil
		},
		"aw6061": func(p *model.HeroStats) (string, error) {
			if p.Medals.Awards[6061] == "" {
				return "6000", nil
			}
			return p.Medals.Awards[6061], nil
		},
		"aw6062": func(p *model.HeroStats) (string, error) {
			if p.Medals.Awards[6062] == "" {
				return "6000", nil
			}
			return p.Medals.Awards[6062], nil
		},
		"aw6063": func(p *model.HeroStats) (string, error) {
			if p.Medals.Awards[6063] == "" {
				return "6000", nil
			}
			return p.Medals.Awards[6063], nil
		},
		"aw6064": func(p *model.HeroStats) (string, error) {
			if p.Medals.Awards[6064] == "" {
				return "6000", nil
			}
			return p.Medals.Awards[6064], nil
		},
		"aw6065": func(p *model.HeroStats) (string, error) {
			if p.Medals.Awards[6065] == "" {
				return "6000", nil
			}
			return p.Medals.Awards[6065], nil
		},
		"aw6066": func(p *model.HeroStats) (string, error) {
			if p.Medals.Awards[6066] == "" {
				return "6000", nil
			}
			return p.Medals.Awards[6066], nil
		},
		"aw6067": func(p *model.HeroStats) (string, error) {
			if p.Medals.Awards[6067] == "" {
				return "6000", nil
			}
			return p.Medals.Awards[6067], nil
		},
		"aw6068": func(p *model.HeroStats) (string, error) {
			if p.Medals.Awards[6068] == "" {
				return "6000", nil
			}
			return p.Medals.Awards[6068], nil
		},
		"aw6069": func(p *model.HeroStats) (string, error) {
			if p.Medals.Awards[6069] == "" {
				return "6000", nil
			}
			return p.Medals.Awards[6069], nil
		},
		"aw6070": func(p *model.HeroStats) (string, error) {
			if p.Medals.Awards[6070] == "" {
				return "6000", nil
			}
			return p.Medals.Awards[6070], nil
		},
		"aw6071": func(p *model.HeroStats) (string, error) {
			if p.Medals.Awards[6071] == "" {
				return "6000", nil
			}
			return p.Medals.Awards[6071], nil
		},
		"aw6072": func(p *model.HeroStats) (string, error) {
			if p.Medals.Awards[6072] == "" {
				return "6000", nil
			}
			return p.Medals.Awards[6072], nil
		},
		"aw6073": func(p *model.HeroStats) (string, error) {
			if p.Medals.Awards[6073] == "" {
				return "6000", nil
			}
			return p.Medals.Awards[6073], nil
		},
		"aw6074": func(p *model.HeroStats) (string, error) {
			if p.Medals.Awards[6074] == "" {
				return "6000", nil
			}
			return p.Medals.Awards[6074], nil
		},
		"aw6075": func(p *model.HeroStats) (string, error) {
			if p.Medals.Awards[6075] == "" {
				return "6000", nil
			}
			return p.Medals.Awards[6075], nil
		},
		"aw6076": func(p *model.HeroStats) (string, error) {
			if p.Medals.Awards[6076] == "" {
				return "6000", nil
			}
			return p.Medals.Awards[6076], nil
		},
		"aw6077": func(p *model.HeroStats) (string, error) {
			if p.Medals.Awards[6077] == "" {
				return "6000", nil
			}
			return p.Medals.Awards[6077], nil
		},
		"aw6078": func(p *model.HeroStats) (string, error) {
			if p.Medals.Awards[6078] == "" {
				return "6000", nil
			}
			return p.Medals.Awards[6078], nil
		},
		"aw6079": func(p *model.HeroStats) (string, error) {
			if p.Medals.Awards[6079] == "" {
				return "6000", nil
			}
			return p.Medals.Awards[6079], nil
		},
		"aw6080": func(p *model.HeroStats) (string, error) {
			if p.Medals.Awards[6080] == "" {
				return "6000", nil
			}
			return p.Medals.Awards[6080], nil
		},
		"aw6081": func(p *model.HeroStats) (string, error) {
			if p.Medals.Awards[6081] == "" {
				return "6000", nil
			}
			return p.Medals.Awards[6081], nil
		},
		"aw6082": func(p *model.HeroStats) (string, error) {
			if p.Medals.Awards[6082] == "" {
				return "6000", nil
			}
			return p.Medals.Awards[6082], nil
		},
		"aw6083": func(p *model.HeroStats) (string, error) {
			if p.Medals.Awards[6083] == "" {
				return "6000", nil
			}
			return p.Medals.Awards[6083], nil
		},
		"aw6084": func(p *model.HeroStats) (string, error) {
			if p.Medals.Awards[6084] == "" {
				return "6000", nil
			}
			return p.Medals.Awards[6084], nil
		},
		"aw6085": func(p *model.HeroStats) (string, error) {
			if p.Medals.Awards[6085] == "" {
				return "6000", nil
			}
			return p.Medals.Awards[6085], nil
		},
		"aw6086": func(p *model.HeroStats) (string, error) {
			if p.Medals.Awards[6086] == "" {
				return "6000", nil
			}
			return p.Medals.Awards[6086], nil
		},
		"aw6087": func(p *model.HeroStats) (string, error) {
			if p.Medals.Awards[6087] == "" {
				return "6000", nil
			}
			return p.Medals.Awards[6087], nil
		},
		"aw6088": func(p *model.HeroStats) (string, error) {
			if p.Medals.Awards[6088] == "" {
				return "6000", nil
			}
			return p.Medals.Awards[6088], nil
		},
		"aw6089": func(p *model.HeroStats) (string, error) {
			if p.Medals.Awards[6089] == "" {
				return "6000", nil
			}
			return p.Medals.Awards[6089], nil
		},
		"aw6090": func(p *model.HeroStats) (string, error) {
			if p.Medals.Awards[6090] == "" {
				return "6000", nil
			}
			return p.Medals.Awards[6090], nil
		},
		"aw6091": func(p *model.HeroStats) (string, error) {
			if p.Medals.Awards[6091] == "" {
				return "6000", nil
			}
			return p.Medals.Awards[6091], nil
		},
		"aw6092": func(p *model.HeroStats) (string, error) {
			if p.Medals.Awards[6092] == "" {
				return "6000", nil
			}
			return p.Medals.Awards[6092], nil
		},
		"aw6093": func(p *model.HeroStats) (string, error) {
			if p.Medals.Awards[6093] == "" {
				return "6000", nil
			}
			return p.Medals.Awards[6093], nil
		},
		"aw6094": func(p *model.HeroStats) (string, error) {
			if p.Medals.Awards[6094] == "" {
				return "6000", nil
			}
			return p.Medals.Awards[6094], nil
		},
		"aw6095": func(p *model.HeroStats) (string, error) {
			if p.Medals.Awards[6095] == "" {
				return "6000", nil
			}
			return p.Medals.Awards[6095], nil
		},
		"aw6096": func(p *model.HeroStats) (string, error) {
			if p.Medals.Awards[6096] == "" {
				return "6000", nil
			}
			return p.Medals.Awards[6096], nil
		},
		"aw6097": func(p *model.HeroStats) (string, error) {
			if p.Medals.Awards[6097] == "" {
				return "6000", nil
			}
			return p.Medals.Awards[6097], nil
		},
		"aw6098": func(p *model.HeroStats) (string, error) {
			if p.Medals.Awards[6098] == "" {
				return "6000", nil
			}
			return p.Medals.Awards[6098], nil
		},
		"aw6099": func(p *model.HeroStats) (string, error) {
			if p.Medals.Awards[6099] == "" {
				return "6000", nil
			}
			return p.Medals.Awards[6099], nil
		},
		"aw6100": func(p *model.HeroStats) (string, error) {
			if p.Medals.Awards[6100] == "" {
				return "6000", nil
			}
			return p.Medals.Awards[6100], nil
		},
		"aw6101": func(p *model.HeroStats) (string, error) {
			if p.Medals.Awards[6101] == "" {
				return "6000", nil
			}
			return p.Medals.Awards[6101], nil
		},
		"aw6102": func(p *model.HeroStats) (string, error) {
			if p.Medals.Awards[6102] == "" {
				return "6000", nil
			}
			return p.Medals.Awards[6102], nil
		},
		"aw6103": func(p *model.HeroStats) (string, error) {
			if p.Medals.Awards[6103] == "" {
				return "6000", nil
			}
			return p.Medals.Awards[6103], nil
		},
		"aw6104": func(p *model.HeroStats) (string, error) {
			if p.Medals.Awards[6104] == "" {
				return "6000", nil
			}
			return p.Medals.Awards[6104], nil
		},
		"aw6105": func(p *model.HeroStats) (string, error) {
			if p.Medals.Awards[6105] == "" {
				return "6000", nil
			}
			return p.Medals.Awards[6105], nil
		},
		"aw6106": func(p *model.HeroStats) (string, error) {
			if p.Medals.Awards[6106] == "" {
				return "6000", nil
			}
			return p.Medals.Awards[6106], nil
		},
		"aw6107": func(p *model.HeroStats) (string, error) {
			if p.Medals.Awards[6107] == "" {
				return "6000", nil
			}
			return p.Medals.Awards[6107], nil
		},
		"aw6108": func(p *model.HeroStats) (string, error) {
			if p.Medals.Awards[6108] == "" {
				return "6000", nil
			}
			return p.Medals.Awards[6108], nil
		},
		"aw6109": func(p *model.HeroStats) (string, error) {
			if p.Medals.Awards[6109] == "" {
				return "6000", nil
			}
			return p.Medals.Awards[6109], nil
		},
		"aw6110": func(p *model.HeroStats) (string, error) {
			if p.Medals.Awards[6110] == "" {
				return "6000", nil
			}
			return p.Medals.Awards[6110], nil
		},
		"aw6111": func(p *model.HeroStats) (string, error) {
			if p.Medals.Awards[6111] == "" {
				return "6000", nil
			}
			return p.Medals.Awards[6111], nil
		},
		"aw6112": func(p *model.HeroStats) (string, error) {
			if p.Medals.Awards[6112] == "" {
				return "6000", nil
			}
			return p.Medals.Awards[6112], nil
		},
		"aw6113": func(p *model.HeroStats) (string, error) {
			if p.Medals.Awards[6113] == "" {
				return "6000", nil
			}
			return p.Medals.Awards[6113], nil
		},
		"aw6114": func(p *model.HeroStats) (string, error) {
			if p.Medals.Awards[6114] == "" {
				return "6000", nil
			}
			return p.Medals.Awards[6114], nil
		},
		"aw6115": func(p *model.HeroStats) (string, error) {
			if p.Medals.Awards[6115] == "" {
				return "6000", nil
			}
			return p.Medals.Awards[6115], nil
		},
		"aw6116": func(p *model.HeroStats) (string, error) {
			if p.Medals.Awards[6116] == "" {
				return "6000", nil
			}
			return p.Medals.Awards[6116], nil
		},
		"aw6117": func(p *model.HeroStats) (string, error) {
			if p.Medals.Awards[6117] == "" {
				return "6000", nil
			}
			return p.Medals.Awards[6117], nil
		},
		"aw6118": func(p *model.HeroStats) (string, error) {
			if p.Medals.Awards[6118] == "" {
				return "6000", nil
			}
			return p.Medals.Awards[6118], nil
		},
		"aw6119": func(p *model.HeroStats) (string, error) {
			if p.Medals.Awards[6119] == "" {
				return "6000", nil
			}
			return p.Medals.Awards[6119], nil
		},
		"aw6120": func(p *model.HeroStats) (string, error) {
			if p.Medals.Awards[6120] == "" {
				return "6000", nil
			}
			return p.Medals.Awards[6120], nil
		},
		"aw6121": func(p *model.HeroStats) (string, error) {
			if p.Medals.Awards[6121] == "" {
				return "6000", nil
			}
			return p.Medals.Awards[6121], nil
		},
		"aw6122": func(p *model.HeroStats) (string, error) {
			if p.Medals.Awards[6122] == "" {
				return "6000", nil
			}
			return p.Medals.Awards[6122], nil
		},
		"aw6123": func(p *model.HeroStats) (string, error) {
			if p.Medals.Awards[6123] == "" {
				return "6000", nil
			}
			return p.Medals.Awards[6123], nil
		},
		"aw6124": func(p *model.HeroStats) (string, error) {
			if p.Medals.Awards[6124] == "" {
				return "6000", nil
			}
			return p.Medals.Awards[6124], nil
		},
		"aw6125": func(p *model.HeroStats) (string, error) {
			if p.Medals.Awards[6125] == "" {
				return "6000", nil
			}
			return p.Medals.Awards[6125], nil
		},
		"aw6126": func(p *model.HeroStats) (string, error) {
			if p.Medals.Awards[6126] == "" {
				return "6000", nil
			}
			return p.Medals.Awards[6126], nil
		},
		"aw6127": func(p *model.HeroStats) (string, error) {
			if p.Medals.Awards[6127] == "" {
				return "6000", nil
			}
			return p.Medals.Awards[6127], nil
		},
		"aw6128": func(p *model.HeroStats) (string, error) {
			if p.Medals.Awards[6128] == "" {
				return "6000", nil
			}
			return p.Medals.Awards[6128], nil
		},
		"aw6129": func(p *model.HeroStats) (string, error) {
			if p.Medals.Awards[6129] == "" {
				return "6000", nil
			}
			return p.Medals.Awards[6129], nil
		},
		"aw6130": func(p *model.HeroStats) (string, error) {
			if p.Medals.Awards[6130] == "" {
				return "6000", nil
			}
			return p.Medals.Awards[6130], nil
		},
		"aw6131": func(p *model.HeroStats) (string, error) {
			if p.Medals.Awards[6131] == "" {
				return "6000", nil
			}
			return p.Medals.Awards[6131], nil
		},
		"aw6132": func(p *model.HeroStats) (string, error) {
			if p.Medals.Awards[6132] == "" {
				return "6000", nil
			}
			return p.Medals.Awards[6132], nil
		},
		"aw6133": func(p *model.HeroStats) (string, error) {
			if p.Medals.Awards[6133] == "" {
				return "6000", nil
			}
			return p.Medals.Awards[6133], nil
		},
		"aw6134": func(p *model.HeroStats) (string, error) {
			if p.Medals.Awards[6134] == "" {
				return "6000", nil
			}
			return p.Medals.Awards[6134], nil
		},
		"aw6135": func(p *model.HeroStats) (string, error) {
			if p.Medals.Awards[6135] == "" {
				return "6000", nil
			}
			return p.Medals.Awards[6135], nil
		},
		"aw6136": func(p *model.HeroStats) (string, error) {
			if p.Medals.Awards[6136] == "" {
				return "6000", nil
			}
			return p.Medals.Awards[6136], nil
		},
		"aw6137": func(p *model.HeroStats) (string, error) {
			if p.Medals.Awards[6137] == "" {
				return "6000", nil
			}
			return p.Medals.Awards[6137], nil
		},
		"aw6138": func(p *model.HeroStats) (string, error) {
			if p.Medals.Awards[6138] == "" {
				return "6000", nil
			}
			return p.Medals.Awards[6138], nil
		},
		"aw6139": func(p *model.HeroStats) (string, error) {
			if p.Medals.Awards[6139] == "" {
				return "6000", nil
			}
			return p.Medals.Awards[6139], nil
		},
		"aw6140": func(p *model.HeroStats) (string, error) {
			if p.Medals.Awards[6140] == "" {
				return "6000", nil
			}
			return p.Medals.Awards[6140], nil
		},
		"aw6141": func(p *model.HeroStats) (string, error) {
			if p.Medals.Awards[6141] == "" {
				return "6000", nil
			}
			return p.Medals.Awards[6141], nil
		},
		"aw6142": func(p *model.HeroStats) (string, error) {
			if p.Medals.Awards[6142] == "" {
				return "6000", nil
			}
			return p.Medals.Awards[6142], nil
		},
		"aw6143": func(p *model.HeroStats) (string, error) {
			if p.Medals.Awards[6143] == "" {
				return "6000", nil
			}
			return p.Medals.Awards[6143], nil
		},
		"aw6144": func(p *model.HeroStats) (string, error) {
			if p.Medals.Awards[6144] == "" {
				return "6000", nil
			}
			return p.Medals.Awards[6144], nil
		},
		"aw6145": func(p *model.HeroStats) (string, error) {
			if p.Medals.Awards[6145] == "" {
				return "6000", nil
			}
			return p.Medals.Awards[6145], nil
		},
		"aw6146": func(p *model.HeroStats) (string, error) {
			if p.Medals.Awards[6146] == "" {
				return "6000", nil
			}
			return p.Medals.Awards[6146], nil
		},
		"aw6147": func(p *model.HeroStats) (string, error) {
			if p.Medals.Awards[6147] == "" {
				return "6000", nil
			}
			return p.Medals.Awards[6147], nil
		},
		"aw6148": func(p *model.HeroStats) (string, error) {
			if p.Medals.Awards[6148] == "" {
				return "6000", nil
			}
			return p.Medals.Awards[6148], nil
		},
		"aw6149": func(p *model.HeroStats) (string, error) {
			if p.Medals.Awards[6149] == "" {
				return "6000", nil
			}
			return p.Medals.Awards[6149], nil
		},
		"aw6150": func(p *model.HeroStats) (string, error) {
			if p.Medals.Awards[6150] == "" {
				return "6000", nil
			}
			return p.Medals.Awards[6150], nil
		},
		"aw6151": func(p *model.HeroStats) (string, error) {
			if p.Medals.Awards[6151] == "" {
				return "6000", nil
			}
			return p.Medals.Awards[6151], nil
		},
		"aw6152": func(p *model.HeroStats) (string, error) {
			if p.Medals.Awards[6152] == "" {
				return "6000", nil
			}
			return p.Medals.Awards[6152], nil
		},
		"aw6153": func(p *model.HeroStats) (string, error) {
			if p.Medals.Awards[6153] == "" {
				return "6000", nil
			}
			return p.Medals.Awards[6153], nil
		},
		"aw6154": func(p *model.HeroStats) (string, error) {
			if p.Medals.Awards[6154] == "" {
				return "6000", nil
			}
			return p.Medals.Awards[6154], nil
		},
		"aw6155": func(p *model.HeroStats) (string, error) {
			if p.Medals.Awards[6155] == "" {
				return "6000", nil
			}
			return p.Medals.Awards[6155], nil
		},
		"aw6156": func(p *model.HeroStats) (string, error) {
			if p.Medals.Awards[6156] == "" {
				return "6000", nil
			}
			return p.Medals.Awards[6156], nil
		},
		"aw6157": func(p *model.HeroStats) (string, error) {
			if p.Medals.Awards[6157] == "" {
				return "6000", nil
			}
			return p.Medals.Awards[6157], nil
		},
		"aw6158": func(p *model.HeroStats) (string, error) {
			if p.Medals.Awards[6158] == "" {
				return "6000", nil
			}
			return p.Medals.Awards[6158], nil
		},
		"aw6159": func(p *model.HeroStats) (string, error) {
			if p.Medals.Awards[6159] == "" {
				return "6000", nil
			}
			return p.Medals.Awards[6159], nil
		},
		"aw6160": func(p *model.HeroStats) (string, error) {
			if p.Medals.Awards[6160] == "" {
				return "6000", nil
			}
			return p.Medals.Awards[6160], nil
		},
		"aw6161": func(p *model.HeroStats) (string, error) {
			if p.Medals.Awards[6161] == "" {
				return "6000", nil
			}
			return p.Medals.Awards[6161], nil
		},
		"aw6162": func(p *model.HeroStats) (string, error) {
			if p.Medals.Awards[6162] == "" {
				return "6000", nil
			}
			return p.Medals.Awards[6162], nil
		},
		"aw6163": func(p *model.HeroStats) (string, error) {
			if p.Medals.Awards[6163] == "" {
				return "6000", nil
			}
			return p.Medals.Awards[6163], nil
		},
		"aw6164": func(p *model.HeroStats) (string, error) {
			if p.Medals.Awards[6164] == "" {
				return "6000", nil
			}
			return p.Medals.Awards[6164], nil
		},
		"aw6165": func(p *model.HeroStats) (string, error) {
			if p.Medals.Awards[6165] == "" {
				return "6000", nil
			}
			return p.Medals.Awards[6165], nil
		},
		"aw6166": func(p *model.HeroStats) (string, error) {
			if p.Medals.Awards[6166] == "" {
				return "6000", nil
			}
			return p.Medals.Awards[6166], nil
		},
		"aw6167": func(p *model.HeroStats) (string, error) {
			if p.Medals.Awards[6167] == "" {
				return "6000", nil
			}
			return p.Medals.Awards[6167], nil
		},
		"aw6168": func(p *model.HeroStats) (string, error) {
			if p.Medals.Awards[6168] == "" {
				return "6000", nil
			}
			return p.Medals.Awards[6168], nil
		},
		"aw6169": func(p *model.HeroStats) (string, error) {
			if p.Medals.Awards[6169] == "" {
				return "6000", nil
			}
			return p.Medals.Awards[6169], nil
		},
		"aw6170": func(p *model.HeroStats) (string, error) {
			if p.Medals.Awards[6170] == "" {
				return "6000", nil
			}
			return p.Medals.Awards[6170], nil
		},
		"aw6171": func(p *model.HeroStats) (string, error) {
			if p.Medals.Awards[6171] == "" {
				return "6000", nil
			}
			return p.Medals.Awards[6171], nil
		},
		"aw6172": func(p *model.HeroStats) (string, error) {
			if p.Medals.Awards[6172] == "" {
				return "6000", nil
			}
			return p.Medals.Awards[6172], nil
		},
		"aw6173": func(p *model.HeroStats) (string, error) {
			if p.Medals.Awards[6173] == "" {
				return "6000", nil
			}
			return p.Medals.Awards[6173], nil
		},
		"aw6174": func(p *model.HeroStats) (string, error) {
			if p.Medals.Awards[6174] == "" {
				return "6000", nil
			}
			return p.Medals.Awards[6174], nil
		},
		"aw6175": func(p *model.HeroStats) (string, error) {
			if p.Medals.Awards[6175] == "" {
				return "6000", nil
			}
			return p.Medals.Awards[6175], nil
		},
		"aw6176": func(p *model.HeroStats) (string, error) {
			if p.Medals.Awards[6176] == "" {
				return "6000", nil
			}
			return p.Medals.Awards[6176], nil
		},
		"aw6177": func(p *model.HeroStats) (string, error) {
			if p.Medals.Awards[6177] == "" {
				return "6000", nil
			}
			return p.Medals.Awards[6177], nil
		},
		"aw6178": func(p *model.HeroStats) (string, error) {
			if p.Medals.Awards[6178] == "" {
				return "6000", nil
			}
			return p.Medals.Awards[6178], nil
		},
		"aw6179": func(p *model.HeroStats) (string, error) {
			if p.Medals.Awards[6179] == "" {
				return "6000", nil
			}
			return p.Medals.Awards[6179], nil
		},
		"aw6180": func(p *model.HeroStats) (string, error) {
			if p.Medals.Awards[6180] == "" {
				return "6000", nil
			}
			return p.Medals.Awards[6180], nil
		},
		"aw6181": func(p *model.HeroStats) (string, error) {
			if p.Medals.Awards[6181] == "" {
				return "6000", nil
			}
			return p.Medals.Awards[6181], nil
		},
		"aw6182": func(p *model.HeroStats) (string, error) {
			if p.Medals.Awards[6182] == "" {
				return "6000", nil
			}
			return p.Medals.Awards[6182], nil
		},
		"mid0": func(p *model.HeroStats) (string, error) {
			if p.Medals.Missions[0] == "" {
				return "0", nil
			}
			return p.Medals.Missions[0], nil
		},
		"mid1": func(p *model.HeroStats) (string, error) {
			if p.Medals.Missions[1] == "" {
				return "0", nil
			}
			return p.Medals.Missions[1], nil
		},
		"mid2": func(p *model.HeroStats) (string, error) {
			if p.Medals.Missions[2] == "" {
				return "0", nil
			}
			return p.Medals.Missions[2], nil
		},
		"c_mid0": func(p *model.HeroStats) (string, error) {
			if p.Medals.PlayedMissions[0] == "" {
				return "0.0000", nil
			}
			return p.Medals.PlayedMissions[0], nil
		},
		"c_mid1": func(p *model.HeroStats) (string, error) {
			if p.Medals.PlayedMissions[1] == "" {
				return "0.0000", nil
			}
			return p.Medals.PlayedMissions[1], nil
		},
		"c_mid2": func(p *model.HeroStats) (string, error) {
			if p.Medals.PlayedMissions[2] == "" {
				return "0.0000", nil
			}
			return p.Medals.PlayedMissions[2], nil
		},
		"c_cmid0": func(p *model.HeroStats) (string, error) {
			if p.Medals.CompletedMissions[0] == "" {
				return "0.0000", nil
			}
			return p.Medals.CompletedMissions[0], nil
		},
		"c_cmid1": func(p *model.HeroStats) (string, error) {
			if p.Medals.CompletedMissions[1] == "" {
				return "0.0000", nil
			}
			return p.Medals.CompletedMissions[1], nil
		},
		"c_cmid2": func(p *model.HeroStats) (string, error) {
			if p.Medals.CompletedMissions[2] == "" {
				return "0.0000", nil
			}
			return p.Medals.CompletedMissions[2], nil
		},
		"m0c0": func(p *model.HeroStats) (string, error) {
			if p.Medals.MissionOne[0] == "" {
				return "0.0000", nil
			}
			return p.Medals.MissionOne[0], nil
		},
		"m0c1": func(p *model.HeroStats) (string, error) {
			if p.Medals.MissionOne[1] == "" {
				return "0.0000", nil
			}
			return p.Medals.MissionOne[1], nil
		},
		"m0c2": func(p *model.HeroStats) (string, error) {
			if p.Medals.MissionOne[2] == "" {
				return "0.0000", nil
			}
			return p.Medals.MissionOne[2], nil
		},
		"m0c3": func(p *model.HeroStats) (string, error) {
			if p.Medals.MissionOne[3] == "" {
				return "0.0000", nil
			}
			return p.Medals.MissionOne[3], nil
		},
		"m0c4": func(p *model.HeroStats) (string, error) {
			if p.Medals.MissionOne[4] == "" {
				return "0.0000", nil
			}
			return p.Medals.MissionOne[4], nil
		},
		"m0c5": func(p *model.HeroStats) (string, error) {
			if p.Medals.MissionOne[5] == "" {
				return "0.0000", nil
			}
			return p.Medals.MissionOne[5], nil
		},
		"m1c0": func(p *model.HeroStats) (string, error) {
			if p.Medals.MissionTwo[0] == "" {
				return "0.0000", nil
			}
			return p.Medals.MissionTwo[0], nil
		},
		"m1c1": func(p *model.HeroStats) (string, error) {
			if p.Medals.MissionTwo[1] == "" {
				return "0.0000", nil
			}
			return p.Medals.MissionTwo[1], nil
		},
		"m1c2": func(p *model.HeroStats) (string, error) {
			if p.Medals.MissionTwo[2] == "" {
				return "0.0000", nil
			}
			return p.Medals.MissionTwo[2], nil
		},
		"m1c3": func(p *model.HeroStats) (string, error) {
			if p.Medals.MissionTwo[3] == "" {
				return "0.0000", nil
			}
			return p.Medals.MissionTwo[3], nil
		},
		"m1c4": func(p *model.HeroStats) (string, error) {
			if p.Medals.MissionTwo[4] == "" {
				return "0.0000", nil
			}
			return p.Medals.MissionTwo[4], nil
		},
		"m1c5": func(p *model.HeroStats) (string, error) {
			if p.Medals.MissionTwo[5] == "" {
				return "0.0000", nil
			}
			return p.Medals.MissionTwo[5], nil
		},
		"m2c0": func(p *model.HeroStats) (string, error) {
			if p.Medals.MissionThree[0] == "" {
				return "0.0000", nil
			}
			return p.Medals.MissionThree[0], nil
		},
		"m2c1": func(p *model.HeroStats) (string, error) {
			if p.Medals.MissionThree[1] == "" {
				return "0.0000", nil
			}
			return p.Medals.MissionThree[1], nil
		},
		"m2c2": func(p *model.HeroStats) (string, error) {
			if p.Medals.MissionThree[2] == "" {
				return "0.0000", nil
			}
			return p.Medals.MissionThree[2], nil
		},
		"m2c3": func(p *model.HeroStats) (string, error) {
			if p.Medals.MissionThree[3] == "" {
				return "0.0000", nil
			}
			return p.Medals.MissionThree[3], nil
		},
		"m2c4": func(p *model.HeroStats) (string, error) {
			if p.Medals.MissionThree[4] == "" {
				return "0.0000", nil
			}
			return p.Medals.MissionThree[4], nil
		},
		"m2c5": func(p *model.HeroStats) (string, error) {
			if p.Medals.MissionThree[5] == "" {
				return "0.0000", nil
			}
			return p.Medals.MissionThree[5], nil
		},
		"c_wmid0": func(p *model.HeroStats) (string, error) {
			if p.Medals.WishedMissions[0] == "" {
				return "6000.0000", nil
			}
			return p.Medals.WishedMissions[0], nil
		},
		"c_wmid1": func(p *model.HeroStats) (string, error) {
			if p.Medals.WishedMissions[1] == "" {
				return "6000.0000", nil
			}
			return p.Medals.WishedMissions[1], nil
		},
		"c_wmid2": func(p *model.HeroStats) (string, error) {
			if p.Medals.WishedMissions[2] == "" {
				return "6000.0000", nil
			}
			return p.Medals.WishedMissions[2], nil
		},
		"startLVL": func(p *model.HeroStats) (string, error) {
			if p.Rounded.StartRank == "" {
				return "0.0000", nil
			}
			return p.Rounded.StartRank, nil
		},
		"roundXP": func(p *model.HeroStats) (string, error) {
			if p.Rounded.RoundXP == "" {
				return "0.0000", nil
			}
			return p.Rounded.RoundXP, nil
		},
		"roundBXP": func(p *model.HeroStats) (string, error) {
			if p.Rounded.RoundBonusXP == "" {
				return "0.0000", nil
			}
			return p.Rounded.RoundBonusXP, nil
		},
		"roundVP": func(p *model.HeroStats) (string, error) {
			if p.Rounded.RoundValorPoints == "" {
				return "0.0000", nil
			}
			return p.Rounded.RoundValorPoints, nil
		},
		"roundBVP": func(p *model.HeroStats) (string, error) {
			if p.Rounded.RoundBonusValorPoints == "" {
				return "0.0000", nil
			}
			return p.Rounded.RoundBonusValorPoints, nil
		},
		"roundHP": func(p *model.HeroStats) (string, error) {
			if p.Rounded.RoundHeroPoints == "" {
				return "0.0000", nil
			}
			return p.Rounded.RoundHeroPoints, nil
		},
		"roundPP": func(p *model.HeroStats) (string, error) {
			if p.Rounded.RoundPrestigePoints == "" {
				return "0.0000", nil
			}
			return p.Rounded.RoundPrestigePoints, nil
		},
		"roundBPP": func(p *model.HeroStats) (string, error) {
			if p.Rounded.RoundBonusPrestigePoints == "" {
				return "0.0000", nil
			}
			return p.Rounded.RoundBonusPrestigePoints, nil
		},
		"totalPP": func(p *model.HeroStats) (string, error) {
			if p.Rounded.TotalPrestigePoints == "" {
				return "0.0000", nil
			}
			return p.Rounded.TotalPrestigePoints, nil
		},
		"cpc": func(p *model.HeroStats) (string, error) {
			if p.Captures.Captures == "" {
				return "0.0000", nil
			}
			return p.Captures.Captures, nil
		},
		"cpa": func(p *model.HeroStats) (string, error) {
			if p.Captures.CapturesAssists == "" {
				return "0.0000", nil
			}
			return p.Captures.CapturesAssists, nil
		},
		"cpd": func(p *model.HeroStats) (string, error) {
			if p.Captures.CaptureDefends == "" {
				return "0.0000", nil
			}
			return p.Captures.CaptureDefends, nil
		},
		"rc": func(p *model.HeroStats) (string, error) {
			if p.Captures.RocketCaptures == "" {
				return "0.0000", nil
			}
			return p.Captures.RocketCaptures, nil
		},
		"ks": func(p *model.HeroStats) (string, error) {
			if p.Streaks.KillStreak == "" {
				return "0.0000", nil
			}
			return p.Streaks.KillStreak, nil
		},
		"ds": func(p *model.HeroStats) (string, error) {
			if p.Streaks.DeadStreak == "" {
				return "0.0000", nil
			}
			return p.Streaks.DeadStreak, nil
		},
		"ft_rs0": func(p *model.HeroStats) (string, error) {
			if p.ByFaction.ScoreByFaction[0] == "" {
				return "0.0000", nil
			}
			return p.ByFaction.ScoreByFaction[0], nil
		},
		"ft_rs1": func(p *model.HeroStats) (string, error) {
			if p.ByFaction.ScoreByFaction[1] == "" {
				return "0.0000", nil
			}
			return p.ByFaction.ScoreByFaction[1], nil
		},
		"ft_ki0": func(p *model.HeroStats) (string, error) {
			if p.ByFaction.KillsByFaction[0] == "" {
				return "0.0000", nil
			}
			return p.ByFaction.KillsByFaction[0], nil
		},
		"ft_ki1": func(p *model.HeroStats) (string, error) {
			if p.ByFaction.KillsByFaction[1] == "" {
				return "0.0000", nil
			}
			return p.ByFaction.KillsByFaction[1], nil
		},
		"ft_dt0": func(p *model.HeroStats) (string, error) {
			if p.ByFaction.DeathsByFaction[0] == "" {
				return "0.0000", nil
			}
			return p.ByFaction.DeathsByFaction[0], nil
		},
		"ft_dt1": func(p *model.HeroStats) (string, error) {
			if p.ByFaction.DeathsByFaction[1] == "" {
				return "0.0000", nil
			}
			return p.ByFaction.DeathsByFaction[1], nil
		},
		"ft_win0": func(p *model.HeroStats) (string, error) {
			if p.ByFaction.WinsByFaction[0] == "" {
				return "0.0000", nil
			}
			return p.ByFaction.WinsByFaction[0], nil
		},
		"ft_win1": func(p *model.HeroStats) (string, error) {
			if p.ByFaction.WinsByFaction[1] == "" {
				return "0.0000", nil
			}
			return p.ByFaction.WinsByFaction[1], nil
		},
		"ft_los0": func(p *model.HeroStats) (string, error) {
			if p.ByFaction.LossesByFaction[0] == "" {
				return "0.0000", nil
			}
			return p.ByFaction.LossesByFaction[0], nil
		},
		"ft_los1": func(p *model.HeroStats) (string, error) {
			if p.ByFaction.LossesByFaction[1] == "" {
				return "0.0000", nil
			}
			return p.ByFaction.LossesByFaction[1], nil
		},
		"fc_rs0": func(p *model.HeroStats) (string, error) {
			if p.ByKit.ScoreByKit[0] == "" {
				return "0.0000", nil
			}
			return p.ByKit.ScoreByKit[0], nil
		},
		"fc_rs1": func(p *model.HeroStats) (string, error) {
			if p.ByKit.ScoreByKit[1] == "" {
				return "0.0000", nil
			}
			return p.ByKit.ScoreByKit[1], nil
		},
		"fc_rs2": func(p *model.HeroStats) (string, error) {
			if p.ByKit.ScoreByKit[2] == "" {
				return "0.0000", nil
			}
			return p.ByKit.ScoreByKit[2], nil
		},
		"fc_ki0": func(p *model.HeroStats) (string, error) {
			if p.ByKit.KillsByKit[0] == "" {
				return "0.0000", nil
			}
			return p.ByKit.KillsByKit[0], nil
		},
		"fc_ki1": func(p *model.HeroStats) (string, error) {
			if p.ByKit.KillsByKit[1] == "" {
				return "0.0000", nil
			}
			return p.ByKit.KillsByKit[1], nil
		},
		"fc_ki2": func(p *model.HeroStats) (string, error) {
			if p.ByKit.KillsByKit[2] == "" {
				return "0.0000", nil
			}
			return p.ByKit.KillsByKit[2], nil
		},
		"fc_dt0": func(p *model.HeroStats) (string, error) {
			if p.ByKit.DeathsByKit[0] == "" {
				return "0.0000", nil
			}
			return p.ByKit.DeathsByKit[0], nil
		},
		"fc_dt1": func(p *model.HeroStats) (string, error) {
			if p.ByKit.DeathsByKit[1] == "" {
				return "0.0000", nil
			}
			return p.ByKit.DeathsByKit[1], nil
		},
		"fc_dt2": func(p *model.HeroStats) (string, error) {
			if p.ByKit.DeathsByKit[2] == "" {
				return "0.0000", nil
			}
			return p.ByKit.DeathsByKit[2], nil
		},
		"fc_win0": func(p *model.HeroStats) (string, error) {
			if p.ByKit.WinsByKit[0] == "" {
				return "0.0000", nil
			}
			return p.ByKit.WinsByKit[0], nil
		},
		"fc_win1": func(p *model.HeroStats) (string, error) {
			if p.ByKit.WinsByKit[1] == "" {
				return "0.0000", nil
			}
			return p.ByKit.WinsByKit[1], nil
		},
		"fc_win2": func(p *model.HeroStats) (string, error) {
			if p.ByKit.WinsByKit[2] == "" {
				return "0.0000", nil
			}
			return p.ByKit.WinsByKit[2], nil
		},
		"fc_los0": func(p *model.HeroStats) (string, error) {
			if p.ByKit.LossesByKit[0] == "" {
				return "0.0000", nil
			}
			return p.ByKit.LossesByKit[0], nil
		},
		"fc_los1": func(p *model.HeroStats) (string, error) {
			if p.ByKit.LossesByKit[1] == "" {
				return "0.0000", nil
			}
			return p.ByKit.LossesByKit[1], nil
		},
		"fc_los2": func(p *model.HeroStats) (string, error) {
			if p.ByKit.LossesByKit[2] == "" {
				return "0.0000", nil
			}
			return p.ByKit.LossesByKit[2], nil
		},
		"kk0": func(p *model.HeroStats) (string, error) {
			if p.Kits.KitKills[0] == "" {
				return "0.0000", nil
			}
			return p.Kits.KitKills[0], nil
		},
		"kk1": func(p *model.HeroStats) (string, error) {
			if p.Kits.KitKills[1] == "" {
				return "0.0000", nil
			}
			return p.Kits.KitKills[1], nil
		},
		"kk2": func(p *model.HeroStats) (string, error) {
			if p.Kits.KitKills[2] == "" {
				return "0.0000", nil
			}
			return p.Kits.KitKills[2], nil
		},
		"kkb0": func(p *model.HeroStats) (string, error) {
			if p.Kits.KitKilledBy[0] == "" {
				return "0.0000", nil
			}
			return p.Kits.KitKilledBy[0], nil
		},
		"kkb1": func(p *model.HeroStats) (string, error) {
			if p.Kits.KitKilledBy[1] == "" {
				return "0.0000", nil
			}
			return p.Kits.KitKilledBy[1], nil
		},
		"kkb2": func(p *model.HeroStats) (string, error) {
			if p.Kits.KitKilledBy[2] == "" {
				return "0.0000", nil
			}
			return p.Kits.KitKilledBy[2], nil
		},
		"ka": func(p *model.HeroStats) (string, error) {
			if p.Teamplay.DamageAssists == "" {
				return "0.0000", nil
			}
			return p.Teamplay.DamageAssists, nil
		},
		"he": func(p *model.HeroStats) (string, error) {
			if p.Teamplay.HealSelf == "" {
				return "0.0000", nil
			}
			return p.Teamplay.HealSelf, nil
		},
		"drka": func(p *model.HeroStats) (string, error) {
			if p.Teamplay.DriverAssists == "" {
				return "0.0000", nil
			}
			return p.Teamplay.DriverAssists, nil
		},
		"c_apr": func(p *model.HeroStats) (string, error) {
			if len(p.Inventory.Appearance) == 0 {
				return "10;978;980", nil
			}
			return strings.Join(p.Inventory.Appearance, ";"), nil
		},
		"c_emo": func(p *model.HeroStats) (string, error) {
			if len(p.Inventory.Emotes) == 0 {
				return "5000;5007;5016;0;0;0;0;0;0", nil
			}
			return strings.Join(p.Inventory.Emotes, ";"), nil
		},
		"c_eqp": func(p *model.HeroStats) (string, error) {
			if len(p.Inventory.Equipment) == 0 {
				return "3190;0;0;3155;0;0;0;0;0;0", nil
			}
			return strings.Join(p.Inventory.Equipment, ";"), nil
		},
		"c_items": func(p *model.HeroStats) (string, error) {
			if len(p.Inventory.Items) == 0 {
				return "2026;2027;2028;2031;2032;2033;2046;2047;2048;2055;2056;2057;2091", nil
			}
			return strings.Join(p.Inventory.Items, ";"), nil
		},
	}
)
