package ranking

// This file was generated by go:generate
// Do not do any modifications here

import (
	"strings"

	"github.com/Synaxis/nfsc-fesl/backend/model"
)

var (
	setters = map[string]Setter{
		"c_ft": func(p *model.HeroStats, value string, pt int) error {
			p.FacialHairType = value
			return nil
		},
		"c_team": func(p *model.HeroStats, value string, pt int) error {
			p.Faction = value
			return nil
		},
		"c_hrc": func(p *model.HeroStats, value string, pt int) error {
			p.HairColor = value
			return nil
		},
		"c_hrs": func(p *model.HeroStats, value string, pt int) error {
			p.HairStyle = value
			return nil
		},
		"c_skc": func(p *model.HeroStats, value string, pt int) error {
			p.SkinColor = value
			return nil
		},
		"c_ltp": func(p *model.HeroStats, value string, pt int) error {
			p.CLtp = value
			return nil
		},
		"c_ltm": func(p *model.HeroStats, value string, pt int) error {
			p.CLtm = value
			return nil
		},
		"c_fhrs": func(p *model.HeroStats, value string, pt int) error {
			p.CFhrs = value
			return nil
		},
		"c_slm": func(p *model.HeroStats, value string, pt int) error {
			p.CSlm = value
			return nil
		},
		"cdm": func(p *model.HeroStats, value string, pt int) error {
			p.Cdm = value
			return nil
		},
		"edm": func(p *model.HeroStats, value string, pt int) error {
			p.Edm = value
			return nil
		},
		"c_kit": func(p *model.HeroStats, value string, pt int) error {
			p.PlayerType = value
			return nil
		},
		"c_wallet_hero": func(p *model.HeroStats, value string, pt int) error {
			p.HeroPoints = value
			return nil
		},
		"c_wallet_valor": func(p *model.HeroStats, value string, pt int) error {
			p.ValorPoints = value
			return nil
		},
		"games": func(p *model.HeroStats, value string, pt int) error {
			p.GamesPlayed = value
			return nil
		},
		"elo": func(p *model.HeroStats, value string, pt int) error {
			p.Elo = value
			return nil
		},
		"level": func(p *model.HeroStats, value string, pt int) error {
			p.Level = value
			return nil
		},
		"xp": func(p *model.HeroStats, value string, pt int) error {
			p.XP = value
			return nil
		},
		"ct": func(p *model.HeroStats, value string, pt int) error {
			p.TimePlayed = value
			return nil
		},
		"ki": func(p *model.HeroStats, value string, pt int) error {
			p.Kills = value
			return nil
		},
		"dt": func(p *model.HeroStats, value string, pt int) error {
			p.Deaths = value
			return nil
		},
		"su": func(p *model.HeroStats, value string, pt int) error {
			p.Suicides = value
			return nil
		},
		"win": func(p *model.HeroStats, value string, pt int) error {
			p.Wins = value
			return nil
		},
		"los": func(p *model.HeroStats, value string, pt int) error {
			p.Losses = value
			return nil
		},
		"fi": func(p *model.HeroStats, value string, pt int) error {
			p.BulletsFired = value
			return nil
		},
		"hi": func(p *model.HeroStats, value string, pt int) error {
			p.BulletsHit = value
			return nil
		},
		"rs": func(p *model.HeroStats, value string, pt int) error {
			p.Score = value
			return nil
		},
		"ts": func(p *model.HeroStats, value string, pt int) error {
			p.TeamScore = value
			return nil
		},
		"ss": func(p *model.HeroStats, value string, pt int) error {
			p.SkillScore = value
			return nil
		},
		"cs": func(p *model.HeroStats, value string, pt int) error {
			p.CaptureScore = value
			return nil
		},
		"prs": func(p *model.HeroStats, value string, pt int) error {
			p.PrestigeLevel = value
			return nil
		},
		"ppt": func(p *model.HeroStats, value string, pt int) error {
			p.PrestigePoints = value
			return nil
		},
		"c_tut": func(p *model.HeroStats, value string, pt int) error {
			p.PlayedTutorial = value
			return nil
		},
		"awybt": func(p *model.HeroStats, value string, pt int) error {
			p.AwayBonusMedal = value
			return nil
		},
		"dmc": func(p *model.HeroStats, value string, pt int) error {
			p.DailyMissionsCompleted = value
			return nil
		},
		"gsco": func(p *model.HeroStats, value string, pt int) error {
			p.Globals.GlobalScore = value
			return nil
		},
		"expts": func(p *model.HeroStats, value string, pt int) error {
			p.Globals.GlobalXP = value
			return nil
		},
		"bnspt": func(p *model.HeroStats, value string, pt int) error {
			p.Globals.GlobalAwayBonus = value
			return nil
		},
		"c_aprweb0": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.WebKey[0] = value
			return nil
		},
		"c_aprweb1": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.WebKey[1] = value
			return nil
		},
		"c_aprweb2": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.WebKey[2] = value
			return nil
		},
		"c_aprweb3": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.WebKey[3] = value
			return nil
		},
		"c_aprweb4": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.WebKey[4] = value
			return nil
		},
		"c_aprweb5": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.WebKey[5] = value
			return nil
		},
		"c_aprweb6": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.WebKey[6] = value
			return nil
		},
		"aw6000": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.Awards[6000] = value
			return nil
		},
		"aw6001": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.Awards[6001] = value
			return nil
		},
		"aw6002": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.Awards[6002] = value
			return nil
		},
		"aw6003": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.Awards[6003] = value
			return nil
		},
		"aw6004": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.Awards[6004] = value
			return nil
		},
		"aw6005": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.Awards[6005] = value
			return nil
		},
		"aw6006": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.Awards[6006] = value
			return nil
		},
		"aw6007": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.Awards[6007] = value
			return nil
		},
		"aw6008": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.Awards[6008] = value
			return nil
		},
		"aw6009": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.Awards[6009] = value
			return nil
		},
		"aw6010": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.Awards[6010] = value
			return nil
		},
		"aw6011": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.Awards[6011] = value
			return nil
		},
		"aw6012": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.Awards[6012] = value
			return nil
		},
		"aw6013": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.Awards[6013] = value
			return nil
		},
		"aw6014": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.Awards[6014] = value
			return nil
		},
		"aw6015": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.Awards[6015] = value
			return nil
		},
		"aw6016": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.Awards[6016] = value
			return nil
		},
		"aw6017": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.Awards[6017] = value
			return nil
		},
		"aw6018": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.Awards[6018] = value
			return nil
		},
		"aw6019": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.Awards[6019] = value
			return nil
		},
		"aw6020": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.Awards[6020] = value
			return nil
		},
		"aw6021": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.Awards[6021] = value
			return nil
		},
		"aw6022": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.Awards[6022] = value
			return nil
		},
		"aw6023": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.Awards[6023] = value
			return nil
		},
		"aw6024": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.Awards[6024] = value
			return nil
		},
		"aw6025": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.Awards[6025] = value
			return nil
		},
		"aw6026": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.Awards[6026] = value
			return nil
		},
		"aw6027": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.Awards[6027] = value
			return nil
		},
		"aw6028": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.Awards[6028] = value
			return nil
		},
		"aw6029": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.Awards[6029] = value
			return nil
		},
		"aw6030": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.Awards[6030] = value
			return nil
		},
		"aw6031": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.Awards[6031] = value
			return nil
		},
		"aw6032": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.Awards[6032] = value
			return nil
		},
		"aw6033": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.Awards[6033] = value
			return nil
		},
		"aw6034": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.Awards[6034] = value
			return nil
		},
		"aw6035": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.Awards[6035] = value
			return nil
		},
		"aw6036": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.Awards[6036] = value
			return nil
		},
		"aw6037": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.Awards[6037] = value
			return nil
		},
		"aw6038": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.Awards[6038] = value
			return nil
		},
		"aw6039": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.Awards[6039] = value
			return nil
		},
		"aw6040": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.Awards[6040] = value
			return nil
		},
		"aw6041": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.Awards[6041] = value
			return nil
		},
		"aw6042": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.Awards[6042] = value
			return nil
		},
		"aw6043": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.Awards[6043] = value
			return nil
		},
		"aw6044": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.Awards[6044] = value
			return nil
		},
		"aw6045": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.Awards[6045] = value
			return nil
		},
		"aw6046": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.Awards[6046] = value
			return nil
		},
		"aw6047": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.Awards[6047] = value
			return nil
		},
		"aw6048": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.Awards[6048] = value
			return nil
		},
		"aw6049": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.Awards[6049] = value
			return nil
		},
		"aw6050": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.Awards[6050] = value
			return nil
		},
		"aw6051": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.Awards[6051] = value
			return nil
		},
		"aw6052": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.Awards[6052] = value
			return nil
		},
		"aw6053": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.Awards[6053] = value
			return nil
		},
		"aw6054": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.Awards[6054] = value
			return nil
		},
		"aw6055": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.Awards[6055] = value
			return nil
		},
		"aw6056": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.Awards[6056] = value
			return nil
		},
		"aw6057": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.Awards[6057] = value
			return nil
		},
		"aw6058": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.Awards[6058] = value
			return nil
		},
		"aw6059": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.Awards[6059] = value
			return nil
		},
		"aw6060": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.Awards[6060] = value
			return nil
		},
		"aw6061": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.Awards[6061] = value
			return nil
		},
		"aw6062": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.Awards[6062] = value
			return nil
		},
		"aw6063": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.Awards[6063] = value
			return nil
		},
		"aw6064": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.Awards[6064] = value
			return nil
		},
		"aw6065": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.Awards[6065] = value
			return nil
		},
		"aw6066": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.Awards[6066] = value
			return nil
		},
		"aw6067": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.Awards[6067] = value
			return nil
		},
		"aw6068": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.Awards[6068] = value
			return nil
		},
		"aw6069": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.Awards[6069] = value
			return nil
		},
		"aw6070": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.Awards[6070] = value
			return nil
		},
		"aw6071": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.Awards[6071] = value
			return nil
		},
		"aw6072": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.Awards[6072] = value
			return nil
		},
		"aw6073": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.Awards[6073] = value
			return nil
		},
		"aw6074": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.Awards[6074] = value
			return nil
		},
		"aw6075": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.Awards[6075] = value
			return nil
		},
		"aw6076": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.Awards[6076] = value
			return nil
		},
		"aw6077": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.Awards[6077] = value
			return nil
		},
		"aw6078": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.Awards[6078] = value
			return nil
		},
		"aw6079": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.Awards[6079] = value
			return nil
		},
		"aw6080": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.Awards[6080] = value
			return nil
		},
		"aw6081": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.Awards[6081] = value
			return nil
		},
		"aw6082": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.Awards[6082] = value
			return nil
		},
		"aw6083": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.Awards[6083] = value
			return nil
		},
		"aw6084": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.Awards[6084] = value
			return nil
		},
		"aw6085": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.Awards[6085] = value
			return nil
		},
		"aw6086": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.Awards[6086] = value
			return nil
		},
		"aw6087": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.Awards[6087] = value
			return nil
		},
		"aw6088": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.Awards[6088] = value
			return nil
		},
		"aw6089": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.Awards[6089] = value
			return nil
		},
		"aw6090": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.Awards[6090] = value
			return nil
		},
		"aw6091": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.Awards[6091] = value
			return nil
		},
		"aw6092": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.Awards[6092] = value
			return nil
		},
		"aw6093": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.Awards[6093] = value
			return nil
		},
		"aw6094": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.Awards[6094] = value
			return nil
		},
		"aw6095": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.Awards[6095] = value
			return nil
		},
		"aw6096": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.Awards[6096] = value
			return nil
		},
		"aw6097": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.Awards[6097] = value
			return nil
		},
		"aw6098": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.Awards[6098] = value
			return nil
		},
		"aw6099": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.Awards[6099] = value
			return nil
		},
		"aw6100": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.Awards[6100] = value
			return nil
		},
		"aw6101": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.Awards[6101] = value
			return nil
		},
		"aw6102": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.Awards[6102] = value
			return nil
		},
		"aw6103": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.Awards[6103] = value
			return nil
		},
		"aw6104": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.Awards[6104] = value
			return nil
		},
		"aw6105": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.Awards[6105] = value
			return nil
		},
		"aw6106": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.Awards[6106] = value
			return nil
		},
		"aw6107": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.Awards[6107] = value
			return nil
		},
		"aw6108": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.Awards[6108] = value
			return nil
		},
		"aw6109": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.Awards[6109] = value
			return nil
		},
		"aw6110": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.Awards[6110] = value
			return nil
		},
		"aw6111": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.Awards[6111] = value
			return nil
		},
		"aw6112": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.Awards[6112] = value
			return nil
		},
		"aw6113": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.Awards[6113] = value
			return nil
		},
		"aw6114": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.Awards[6114] = value
			return nil
		},
		"aw6115": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.Awards[6115] = value
			return nil
		},
		"aw6116": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.Awards[6116] = value
			return nil
		},
		"aw6117": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.Awards[6117] = value
			return nil
		},
		"aw6118": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.Awards[6118] = value
			return nil
		},
		"aw6119": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.Awards[6119] = value
			return nil
		},
		"aw6120": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.Awards[6120] = value
			return nil
		},
		"aw6121": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.Awards[6121] = value
			return nil
		},
		"aw6122": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.Awards[6122] = value
			return nil
		},
		"aw6123": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.Awards[6123] = value
			return nil
		},
		"aw6124": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.Awards[6124] = value
			return nil
		},
		"aw6125": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.Awards[6125] = value
			return nil
		},
		"aw6126": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.Awards[6126] = value
			return nil
		},
		"aw6127": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.Awards[6127] = value
			return nil
		},
		"aw6128": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.Awards[6128] = value
			return nil
		},
		"aw6129": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.Awards[6129] = value
			return nil
		},
		"aw6130": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.Awards[6130] = value
			return nil
		},
		"aw6131": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.Awards[6131] = value
			return nil
		},
		"aw6132": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.Awards[6132] = value
			return nil
		},
		"aw6133": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.Awards[6133] = value
			return nil
		},
		"aw6134": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.Awards[6134] = value
			return nil
		},
		"aw6135": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.Awards[6135] = value
			return nil
		},
		"aw6136": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.Awards[6136] = value
			return nil
		},
		"aw6137": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.Awards[6137] = value
			return nil
		},
		"aw6138": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.Awards[6138] = value
			return nil
		},
		"aw6139": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.Awards[6139] = value
			return nil
		},
		"aw6140": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.Awards[6140] = value
			return nil
		},
		"aw6141": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.Awards[6141] = value
			return nil
		},
		"aw6142": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.Awards[6142] = value
			return nil
		},
		"aw6143": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.Awards[6143] = value
			return nil
		},
		"aw6144": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.Awards[6144] = value
			return nil
		},
		"aw6145": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.Awards[6145] = value
			return nil
		},
		"aw6146": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.Awards[6146] = value
			return nil
		},
		"aw6147": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.Awards[6147] = value
			return nil
		},
		"aw6148": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.Awards[6148] = value
			return nil
		},
		"aw6149": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.Awards[6149] = value
			return nil
		},
		"aw6150": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.Awards[6150] = value
			return nil
		},
		"aw6151": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.Awards[6151] = value
			return nil
		},
		"aw6152": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.Awards[6152] = value
			return nil
		},
		"aw6153": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.Awards[6153] = value
			return nil
		},
		"aw6154": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.Awards[6154] = value
			return nil
		},
		"aw6155": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.Awards[6155] = value
			return nil
		},
		"aw6156": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.Awards[6156] = value
			return nil
		},
		"aw6157": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.Awards[6157] = value
			return nil
		},
		"aw6158": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.Awards[6158] = value
			return nil
		},
		"aw6159": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.Awards[6159] = value
			return nil
		},
		"aw6160": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.Awards[6160] = value
			return nil
		},
		"aw6161": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.Awards[6161] = value
			return nil
		},
		"aw6162": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.Awards[6162] = value
			return nil
		},
		"aw6163": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.Awards[6163] = value
			return nil
		},
		"aw6164": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.Awards[6164] = value
			return nil
		},
		"aw6165": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.Awards[6165] = value
			return nil
		},
		"aw6166": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.Awards[6166] = value
			return nil
		},
		"aw6167": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.Awards[6167] = value
			return nil
		},
		"aw6168": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.Awards[6168] = value
			return nil
		},
		"aw6169": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.Awards[6169] = value
			return nil
		},
		"aw6170": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.Awards[6170] = value
			return nil
		},
		"aw6171": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.Awards[6171] = value
			return nil
		},
		"aw6172": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.Awards[6172] = value
			return nil
		},
		"aw6173": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.Awards[6173] = value
			return nil
		},
		"aw6174": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.Awards[6174] = value
			return nil
		},
		"aw6175": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.Awards[6175] = value
			return nil
		},
		"aw6176": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.Awards[6176] = value
			return nil
		},
		"aw6177": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.Awards[6177] = value
			return nil
		},
		"aw6178": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.Awards[6178] = value
			return nil
		},
		"aw6179": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.Awards[6179] = value
			return nil
		},
		"aw6180": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.Awards[6180] = value
			return nil
		},
		"aw6181": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.Awards[6181] = value
			return nil
		},
		"aw6182": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.Awards[6182] = value
			return nil
		},
		"mid0": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.Missions[0] = value
			return nil
		},
		"mid1": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.Missions[1] = value
			return nil
		},
		"mid2": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.Missions[2] = value
			return nil
		},
		"c_mid0": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.PlayedMissions[0] = value
			return nil
		},
		"c_mid1": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.PlayedMissions[1] = value
			return nil
		},
		"c_mid2": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.PlayedMissions[2] = value
			return nil
		},
		"c_cmid0": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.CompletedMissions[0] = value
			return nil
		},
		"c_cmid1": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.CompletedMissions[1] = value
			return nil
		},
		"c_cmid2": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.CompletedMissions[2] = value
			return nil
		},
		"m0c0": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.MissionOne[0] = value
			return nil
		},
		"m0c1": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.MissionOne[1] = value
			return nil
		},
		"m0c2": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.MissionOne[2] = value
			return nil
		},
		"m0c3": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.MissionOne[3] = value
			return nil
		},
		"m0c4": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.MissionOne[4] = value
			return nil
		},
		"m0c5": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.MissionOne[5] = value
			return nil
		},
		"m1c0": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.MissionTwo[0] = value
			return nil
		},
		"m1c1": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.MissionTwo[1] = value
			return nil
		},
		"m1c2": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.MissionTwo[2] = value
			return nil
		},
		"m1c3": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.MissionTwo[3] = value
			return nil
		},
		"m1c4": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.MissionTwo[4] = value
			return nil
		},
		"m1c5": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.MissionTwo[5] = value
			return nil
		},
		"m2c0": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.MissionThree[0] = value
			return nil
		},
		"m2c1": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.MissionThree[1] = value
			return nil
		},
		"m2c2": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.MissionThree[2] = value
			return nil
		},
		"m2c3": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.MissionThree[3] = value
			return nil
		},
		"m2c4": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.MissionThree[4] = value
			return nil
		},
		"m2c5": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.MissionThree[5] = value
			return nil
		},
		"c_wmid0": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.WishedMissions[0] = value
			return nil
		},
		"c_wmid1": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.WishedMissions[1] = value
			return nil
		},
		"c_wmid2": func(p *model.HeroStats, value string, pt int) error {
			p.Medals.WishedMissions[2] = value
			return nil
		},
		"startLVL": func(p *model.HeroStats, value string, pt int) error {
			p.Rounded.StartRank = value
			return nil
		},
		"roundXP": func(p *model.HeroStats, value string, pt int) error {
			p.Rounded.RoundXP = value
			return nil
		},
		"roundBXP": func(p *model.HeroStats, value string, pt int) error {
			p.Rounded.RoundBonusXP = value
			return nil
		},
		"roundVP": func(p *model.HeroStats, value string, pt int) error {
			p.Rounded.RoundValorPoints = value
			return nil
		},
		"roundBVP": func(p *model.HeroStats, value string, pt int) error {
			p.Rounded.RoundBonusValorPoints = value
			return nil
		},
		"roundHP": func(p *model.HeroStats, value string, pt int) error {
			p.Rounded.RoundHeroPoints = value
			return nil
		},
		"roundPP": func(p *model.HeroStats, value string, pt int) error {
			p.Rounded.RoundPrestigePoints = value
			return nil
		},
		"roundBPP": func(p *model.HeroStats, value string, pt int) error {
			p.Rounded.RoundBonusPrestigePoints = value
			return nil
		},
		"totalPP": func(p *model.HeroStats, value string, pt int) error {
			p.Rounded.TotalPrestigePoints = value
			return nil
		},
		"cpc": func(p *model.HeroStats, value string, pt int) error {
			p.Captures.Captures = value
			return nil
		},
		"cpa": func(p *model.HeroStats, value string, pt int) error {
			p.Captures.CapturesAssists = value
			return nil
		},
		"cpd": func(p *model.HeroStats, value string, pt int) error {
			p.Captures.CaptureDefends = value
			return nil
		},
		"rc": func(p *model.HeroStats, value string, pt int) error {
			p.Captures.RocketCaptures = value
			return nil
		},
		"ks": func(p *model.HeroStats, value string, pt int) error {
			p.Streaks.KillStreak = value
			return nil
		},
		"ds": func(p *model.HeroStats, value string, pt int) error {
			p.Streaks.DeadStreak = value
			return nil
		},
		"ft_rs0": func(p *model.HeroStats, value string, pt int) error {
			p.ByFaction.ScoreByFaction[0] = value
			return nil
		},
		"ft_rs1": func(p *model.HeroStats, value string, pt int) error {
			p.ByFaction.ScoreByFaction[1] = value
			return nil
		},
		"ft_ki0": func(p *model.HeroStats, value string, pt int) error {
			p.ByFaction.KillsByFaction[0] = value
			return nil
		},
		"ft_ki1": func(p *model.HeroStats, value string, pt int) error {
			p.ByFaction.KillsByFaction[1] = value
			return nil
		},
		"ft_dt0": func(p *model.HeroStats, value string, pt int) error {
			p.ByFaction.DeathsByFaction[0] = value
			return nil
		},
		"ft_dt1": func(p *model.HeroStats, value string, pt int) error {
			p.ByFaction.DeathsByFaction[1] = value
			return nil
		},
		"ft_win0": func(p *model.HeroStats, value string, pt int) error {
			p.ByFaction.WinsByFaction[0] = value
			return nil
		},
		"ft_win1": func(p *model.HeroStats, value string, pt int) error {
			p.ByFaction.WinsByFaction[1] = value
			return nil
		},
		"ft_los0": func(p *model.HeroStats, value string, pt int) error {
			p.ByFaction.LossesByFaction[0] = value
			return nil
		},
		"ft_los1": func(p *model.HeroStats, value string, pt int) error {
			p.ByFaction.LossesByFaction[1] = value
			return nil
		},
		"fc_rs0": func(p *model.HeroStats, value string, pt int) error {
			p.ByKit.ScoreByKit[0] = value
			return nil
		},
		"fc_rs1": func(p *model.HeroStats, value string, pt int) error {
			p.ByKit.ScoreByKit[1] = value
			return nil
		},
		"fc_rs2": func(p *model.HeroStats, value string, pt int) error {
			p.ByKit.ScoreByKit[2] = value
			return nil
		},
		"fc_ki0": func(p *model.HeroStats, value string, pt int) error {
			p.ByKit.KillsByKit[0] = value
			return nil
		},
		"fc_ki1": func(p *model.HeroStats, value string, pt int) error {
			p.ByKit.KillsByKit[1] = value
			return nil
		},
		"fc_ki2": func(p *model.HeroStats, value string, pt int) error {
			p.ByKit.KillsByKit[2] = value
			return nil
		},
		"fc_dt0": func(p *model.HeroStats, value string, pt int) error {
			p.ByKit.DeathsByKit[0] = value
			return nil
		},
		"fc_dt1": func(p *model.HeroStats, value string, pt int) error {
			p.ByKit.DeathsByKit[1] = value
			return nil
		},
		"fc_dt2": func(p *model.HeroStats, value string, pt int) error {
			p.ByKit.DeathsByKit[2] = value
			return nil
		},
		"fc_win0": func(p *model.HeroStats, value string, pt int) error {
			p.ByKit.WinsByKit[0] = value
			return nil
		},
		"fc_win1": func(p *model.HeroStats, value string, pt int) error {
			p.ByKit.WinsByKit[1] = value
			return nil
		},
		"fc_win2": func(p *model.HeroStats, value string, pt int) error {
			p.ByKit.WinsByKit[2] = value
			return nil
		},
		"fc_los0": func(p *model.HeroStats, value string, pt int) error {
			p.ByKit.LossesByKit[0] = value
			return nil
		},
		"fc_los1": func(p *model.HeroStats, value string, pt int) error {
			p.ByKit.LossesByKit[1] = value
			return nil
		},
		"fc_los2": func(p *model.HeroStats, value string, pt int) error {
			p.ByKit.LossesByKit[2] = value
			return nil
		},
		"kk0": func(p *model.HeroStats, value string, pt int) error {
			p.Kits.KitKills[0] = value
			return nil
		},
		"kk1": func(p *model.HeroStats, value string, pt int) error {
			p.Kits.KitKills[1] = value
			return nil
		},
		"kk2": func(p *model.HeroStats, value string, pt int) error {
			p.Kits.KitKills[2] = value
			return nil
		},
		"kkb0": func(p *model.HeroStats, value string, pt int) error {
			p.Kits.KitKilledBy[0] = value
			return nil
		},
		"kkb1": func(p *model.HeroStats, value string, pt int) error {
			p.Kits.KitKilledBy[1] = value
			return nil
		},
		"kkb2": func(p *model.HeroStats, value string, pt int) error {
			p.Kits.KitKilledBy[2] = value
			return nil
		},
		"ka": func(p *model.HeroStats, value string, pt int) error {
			p.Teamplay.DamageAssists = value
			return nil
		},
		"he": func(p *model.HeroStats, value string, pt int) error {
			p.Teamplay.HealSelf = value
			return nil
		},
		"drka": func(p *model.HeroStats, value string, pt int) error {
			p.Teamplay.DriverAssists = value
			return nil
		},
		"c_apr": func(p *model.HeroStats, value string, pt int) error {
			p.Inventory.Appearance = strings.Split(value, ";")
			return nil
		},
		"c_emo": func(p *model.HeroStats, value string, pt int) error {
			p.Inventory.Emotes = strings.Split(value, ";")
			return nil
		},
		"c_eqp": func(p *model.HeroStats, value string, pt int) error {
			p.Inventory.Equipment = strings.Split(value, ";")
			return nil
		},
		"c_items": func(p *model.HeroStats, value string, pt int) error {
			p.Inventory.Items = strings.Split(value, ";")
			return nil
		},
	}
)
